export const AGENTS = [
  {
    id: "technical",
    fn: "analyze_technical",
    name: "Technical",
    team: "Technical",
    weight: 0.35,
    description: "Trend, momentum and moving averages",
  },
  {
    id: "volume",
    fn: "analyze_volume",
    name: "Volume",
    team: "Technical",
    weight: 0.35,
    description: "OBV and volume flow analysis",
  },
  {
    id: "volatility",
    fn: "analyze_volatility",
    name: "Volatility",
    team: "Technical",
    weight: 0.35,
    description: "Bollinger bands and band squeeze",
  },
  {
    id: "pattern",
    fn: "analyze_pattern",
    name: "Pattern",
    team: "Technical",
    weight: 0.35,
    description: "Breakouts and chart patterns",
  },
  {
    id: "sentiment",
    fn: "analyze_sentiment",
    name: "Sentiment",
    team: "Market Intel",
    weight: 0.25,
    description: "News scoring and the Fear & Greed index",
  },
  {
    id: "onchain",
    fn: "analyze_onchain",
    name: "On-chain",
    team: "Market Intel",
    weight: 0.25,
    description: "Whale activity and exchange flows",
  },
  {
    id: "macro",
    fn: "analyze_macro",
    name: "Macro",
    team: "Market Intel",
    weight: 0.25,
    description: "Rate policy, DXY and inflation",
  },
  {
    id: "correlation",
    fn: "analyze_correlation",
    name: "Correlation",
    team: "Market Intel",
    weight: 0.25,
    description: "Cross-asset correlation",
  },
  {
    id: "risk",
    fn: "analyze_risk",
    name: "Risk",
    team: "Risk",
    weight: 0.2,
    description: "ATR stops and position sizing",
  },
  {
    id: "sniper",
    fn: "scan_sniper",
    name: "Sniper",
    team: "Sniper",
    weight: 0,
    description: "Signal-only memecoin scan",
  },
];
